/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal_fisicai;

/**
 *
 * @author donovanpc
 */
public class Panel_ConversorDeUnidades extends javax.swing.JFrame {

    /**
     * Creates new form Panel_ConversorDeUnidades
     */
    public Panel_ConversorDeUnidades() {
        initComponents();

            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Conversor de unidades");

        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Coloca un número:");

        jLabel3.setText("Convertir de:");

        jLabel4.setText("a");

        jLabel5.setText("Resultado:");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Longitud", "Masa", "Tiempo" }));
        jComboBox3.setSelectedIndex(-1);
        jComboBox3.setToolTipText("");

        jLabel6.setText("Primero, escoge unidad a tratar");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2)
                        .addGap(136, 136, 136)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Panel_Inicial panel_Inicial = new Panel_Inicial();
        panel_Inicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String unidad =  jComboBox3.getSelectedItem().toString();
        if(unidad.equals("Longitud")){
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            jComboBox1.addItem("Metros");
            jComboBox1.addItem("Kilometros");
            jComboBox1.addItem("Millas");
            jComboBox1.addItem("Pies");
            jComboBox1.addItem("Centímetros");
            jComboBox1.addItem("Pulgadas");
            jComboBox2.addItem("Metros");
            jComboBox2.addItem("Kilometros");
            jComboBox2.addItem("Millas");
            jComboBox2.addItem("Pies");
            jComboBox2.addItem("Centímetros");
            jComboBox2.addItem("Pulgadas");
        }else if(unidad.equals("Masa")){
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Kilogramos");
            jComboBox1.addItem("Gramo");
            jComboBox1.addItem("Libra");
            jComboBox1.addItem("Onza");
            jComboBox2.addItem("Kilogramo");
            jComboBox2.addItem("Gramo");
            jComboBox2.addItem("Libra");
            jComboBox2.addItem("Onza");            
        }else if(unidad.equals("Tiempo")){  
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();            
            jComboBox1.addItem("Segundos");
            jComboBox1.addItem("Minutos");
            jComboBox1.addItem("Horas");
            jComboBox1.addItem("Días");
            jComboBox1.addItem("Años");
            jComboBox2.addItem("Segundos");
            jComboBox2.addItem("Minutos");
            jComboBox2.addItem("Horas");
            jComboBox2.addItem("Días");
            jComboBox2.addItem("Años");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String de_dato = jComboBox1.getSelectedItem().toString();
        String para_dato = jComboBox2.getSelectedItem().toString();
        Double num = Double.parseDouble(jTextField1.getText());
        
        var resultado = calcular(de_dato, para_dato, num);
        jTextField2.setText(String.valueOf(resultado));
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    private Double calcular(String de, String para, Double num){
        String selecciones = de + para;
        System.out.println(selecciones);
        Double resultado = 0.0;
        switch (selecciones) {
            case "MetrosMetros":
                resultado = 1.0;
                break;
            case "MetrosMillas":
                resultado = num / 1609;
                break;
            case "MetroPies":
                resultado = num * 3.281;
                break;
            case "MetroCentímetros":
                resultado = num * 100;
                break;
            case "MetroPulgadas":
                resultado = num * 39.37;
                break;
            case "MetrosKilometros":
                resultado = num / 1000;
                break;                
            case "KilometrosMetros":
                resultado = num  * 1000;
                break;
            case "KilometrosMillas":
                resultado = num / 1.609;
                break;
            case "KilometrosPies":
                resultado = num * 3281;
                break;
            case "KilometrosCentímetros":
                resultado = num  * 100000;
                break;
            case "KilometrosPulgadas":
                resultado = num  * 39370;
                break;
            case "KilometrosKilometros":
                resultado = 1.0;
                break;
            case "MillasKilometros":
                resultado = num * 1.609;
                break;
            case "MillasMillas":
                resultado = 1.0;
                break;
            case "MillasPies":
                resultado = num * 63360;
                break;
            case "MillasCentímetros":
                resultado = num * 160900;
                break;
            case "MillasPulgadas":
                resultado = num  * 63360;
                break;
            case "PiesMetros":
                resultado = num / 3.281;
                break;
            case "PiesKilometros":
                resultado = num  * 3281;
                break;
            case "PiesMillas":
                resultado = num / 5280;
                break;
            case "PiesPies":
                resultado = 1.0;
                break;
            case "PiesCentímetros":
                resultado = num * 30.48;
                break;
            case "PiesPulgadas":
                resultado = num * 12;
                break;
            case "CentímetrosMetros":
                resultado = num * 100;
                break;
            case "CentímetrosKilometros":
                resultado = num * 100000;
                break;
            case "CentímetrosMillas":
                resultado = num  / 160900;
                break;
            case "CentímetrosPies":
                resultado = num / 30.48;
                break;
            case "CentímetrosCentímetros":
                resultado = 1.0;
                break;
            case "CentímetrosPulgadas":
                resultado = num / 2.54;
                break;
            case "PulgadasMetros":
                resultado = num / 39.37;
                break;
            case "PulgadasKilometros":
                resultado = num / 39370;
                break;
            case "PulgadasMillas":
                resultado = num / 63360;
                break;
            case "PulgadasPies":
                resultado = num / 12;
                break;
            case "PulgadasCentímetros":
                resultado = num * 2.54;
                break;
            case "PulgadasPulgadas":
                resultado = 1.0;
                break;
            case "KilogramoKilogramo":
                resultado = 1.0;
                break;
            case "KilogramoGramo":
                resultado = num * 1000;
                break;
            case "KilogramoLibra":
                resultado = num * 2.205;
                break;
            case "KilogramoOnzas":
                resultado = num * 35.274;
                break;
            case "GramoKilogramo":
                resultado = num / 1000;
                break;
            case "GramoGramo":
                resultado = 1.0;
                break;
            case "GramoLibra":
                resultado = num / 453.6;
                break;
            case "GramoOnzas":
                resultado = num / 28.35;
                break;
            case "LibraKilogramo":
                resultado = num / 2.205;
                break;
            case "LibraGramo":
                resultado = num * 453.6;
                break;
            case "LibraLibra":
                resultado = 1.0;
                break;
            case "LibraOnzas":
                resultado = num * 16;
                break;
            case "OnzasKilogramo":
                resultado = num / 35.274;
                break;
            case "OnzasGramo":
                resultado = num * 28.35;
                break;
            case "OnzasLibra":
                resultado = num / 16;
                break;
            case "OnzasOnzas":
                resultado = 1.0;
                break;
            case "SegundosSegundos":
                resultado = 1.0;
                break;
            case "SegundosMinutos":
                resultado = num / 60;
                break;
            case "SegundosHoras":
                resultado = num / 3600;
                break;
            case "SegundosDías":
                resultado = num / 86400;
                break;
            case "SegundosAños":
                resultado = num / 31536000;
                break;
            case "MinutosSegundos":
                resultado = num * 60;
                break;
            case "MinutosMinutos":
                resultado = 1.0;
                break;
            case "MinutosHoras":
                resultado = num / 60;
                break;
            case "MinutosDías":
                resultado = num / 1440;
                break;
            case "MinutosAños":
                resultado = num / 525600;
                break;
            case "HorasSegundos":
                resultado = num * 3600;
                break;
            case "HorasMinutos":
                resultado = num * 60;
                break;
            case "HorasHoras":
                resultado = 1.0;
                break;
            case "HorasDías":
                resultado = num / 24;
                break;
            case "HorasAños":
                resultado = num / 8760;
                break;
            case "DíasSegundos":
                resultado = num * 86400;
                break;
            case "DíasMinutos":
                resultado = num * 1440;
                break;
            case "DíasHoras":
                resultado = num * 24;
                break;
            case "DíasDías":
                resultado = 1.0;
                break;
            case "DíasAños":
                resultado = num / 365;
                break;
            case "AñosSegundos":
                resultado = num * 31536000;
                break;
            case "AñosMinutos":
                resultado = num * 525600;
                break;
            case "AñosHoras":
                resultado = num * 8760;
                break;
            case "AñosDías":
                resultado = num * 365;
                break;
            case "AñosAños":
                resultado = 1.0;
                break;    
            default:
                throw new AssertionError();
        }
        
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
